name: Action Bot Scheduler

on:
  push:
    branches:
      - master # Run on push to master

  schedule:
    - cron: "0 */4 * * *" # Run every 4 hours
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: magic setup
        uses: actions/setup-node@v1
        with:
          node-version: 14.6.0

      - run: yarn

      - run: node .
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          USER: ${{ secrets.USER }}

      - name: Commit new version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bot] update README.md"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: master # The branch the action should deploy to.
          folder: . # The folder the action should deploy.
